# fly.toml app configuration file generated for fiction-docs on 2024-03-16T08:46:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fiction-docs'
primary_region = 'lax'

[build]
dockerfile = "./static.Dockerfile"
build-target = "fiction-docs"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
