version: 2.1

executors:
  node:
    parameters:
      browsers:
        type: boolean
        default: false
    docker:
      - image: circleci/node:latest<<# parameters.browsers >>-browsers<</ parameters.browsers >>
    working_directory: ~/project
    environment:
      NODE_ENV: test
      NODE_OPTIONS: --max_old_space_size=8192

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

commands:
  attach-project:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
  store-test-results:
    steps:
      - store_test_results:
          path: reports/junit
  release:
    steps:
      - attach-project
      - run:
          name: release
          command: |
            if [ -z "$COMMIT_MSG" ]; then
              COMMIT_MSG=$(git --no-pager log --pretty=full -n1 $CIRCLE_SHA1)
            fi
            if echo "$COMMIT_MSG" | grep -o "\[release\]"; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              yarn lerna version --yes --no-git-tag-version --no-push
              PACKAGE_SUFFIX=edge yarn build
              if [ "$CIRCLE_BRANCH" = "next" ]; then tag="--tag next"; fi
              ./scripts/workspace-run npm publish $tag -q
            else
              echo "Release phase is skipped."
            fi
release_branches: &release_branches
  branches:
    only:
      - dev
      - next

jobs:
  # --------------------------------------------------------------------------
  # Phase 1: Setup
  # --------------------------------------------------------------------------
  setup:
    executor: node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: lock-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      # Save cache
      - save_cache:
          key: lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - "@factor/*/node_modules"

      # Persist workspace
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - "@factor/*/node_modules"
            - "@factor/*/dist"

  # --------------------------------------------------------------------------
  # Phase 2: Lint + Audit + Build
  # --------------------------------------------------------------------------
  lint:
    executor: node
    steps:
      - attach-project
      - run:
          name: Lint
          command: yarn test:lint

  audit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Security Audit
          command: yarn audit || true

  analyze:
    executor: node
    steps:
      - attach-project
      - sonarcloud/scan

  build:
    executor: node
    steps:
      - attach-project
      - run:
          name: Build Fixtures
          command: yarn test:fixtures -i --coverage && yarn test:coverage -F fixtures
          environment:
            JEST_JUNIT_OUTPUT_NAME: fixtures.xml
      - store-test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - test/fixtures

  # --------------------------------------------------------------------------
  # Phase 3: Unit and E2E tests
  # --------------------------------------------------------------------------
  test-unit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Unit Tests
          command: yarn test:unit -w=2 --coverage && yarn test:coverage -F unit
          environment:
            JEST_JUNIT_OUTPUT_NAME: unit.xml
      - store-test-results

  # --------------------------------------------------------------------------
  # Phase 4: Release (dev branch only)
  # --------------------------------------------------------------------------
  release-commit:
    executor: node
    steps:
      - release

  release-nightly:
    executor: node
    steps:
      - release
    environment:
      COMMIT_MSG: "[release]"

# Workflow definition
workflows:
  version: 2

  # Build and test after each commit
  # Manually release on release branches
  commit:
    jobs:
      - setup
      - lint: { requires: [setup] }
      - audit: { requires: [setup] }
      - analyze: { requires: [setup], context: SonarCloud }
      - build: { requires: [setup] }
      - test-unit: { requires: [build] }
      - release-commit:
          requires: [build, lint, audit, test-unit]
          filters:
            <<: *release_branches
