version: 2.1

executors:
  node:
    parameters:
      browsers:
        type: boolean
        default: false
    docker:
      - image: circleci/node:latest<<# parameters.browsers >>-browsers<</ parameters.browsers >>
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/project
    environment:
      NODE_ENV: test
      NODE_OPTIONS: --max_old_space_size=8192

orbs:
  cypress: cypress-io/cypress@1

commands:
  attach-project:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
  store-test-results:
    steps:
      - store_test_results:
          path: reports/junit
  release:
    steps:
      - attach-project
      - run:
          name: release
          command: |
            if [ -z "$COMMIT_MSG" ]; then
              COMMIT_MSG=$(git --no-pager log --pretty=full -n1 $CIRCLE_SHA1)
            fi
            if echo "$COMMIT_MSG" | grep -o "\[release\]"; then
              git config --global user.email "$GIT_AUTHOR_EMAIL"
              git config --global user.name "$GIT_AUTHOR_NAME"
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              if [ "$CIRCLE_BRANCH" = "staging" ]; then tag="--tag staging"; fi
              yarn lerna publish patch --yes
            else
              echo "Release phase is skipped."
            fi
release_branches: &release_branches
  branches:
    only:
      - development
      - staging
      - release

jobs:
  # --------------------------------------------------------------------------
  # Phase 1: Setup
  # --------------------------------------------------------------------------
  setup:
    executor: node
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: lock-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile --non-interactive

      # Save cache
      - save_cache:
          key: lock-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - "@factor/*/node_modules"
            - ~/.cache  ## cache both yarn and Cypress!

      # Persist workspace
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
            - "@factor/*/node_modules"
            - "@factor/*/dist"
            - /*/.cache
            - /home/circleci/.cache/Cypress 

  # --------------------------------------------------------------------------
  # Phase 2: Lint + Audit + Build
  # --------------------------------------------------------------------------
  lint:
    executor: node
    steps:
      - attach-project
      - run:
          name: Lint
          command: yarn test:lint

  audit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Security Audit
          command: yarn audit || true

  build:
    executor: node
    steps:
      - attach-project
      - run:
          name: Build Fixtures
          command: yarn test:builds --runInBand --collectCoverage && yarn test:coverage -F builds
          environment:
            JEST_JUNIT_OUTPUT_NAME: builds.xml
      - store-test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - test/builds

  test-integration:
    executor: node
    steps:
      - attach-project
      - run:
          name: Integration Tests
          command: yarn test:integration --runInBand --collectCoverage && yarn test:coverage -F integration
          environment:
            JEST_JUNIT_OUTPUT_NAME: integration.xml
      - store-test-results

  # --------------------------------------------------------------------------
  # Phase 3: Unit and E2E tests
  # --------------------------------------------------------------------------
  test-unit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Unit Tests
          command: yarn test:unit --runInBand --collectCoverage && yarn test:coverage -F unit
          environment:
            JEST_JUNIT_OUTPUT_NAME: unit.xml
      - store-test-results
  
  test-e2e: 
    executor: node
    steps: 
      - attach-project
      - run:
          name: e2e
          command: "yarn test:e2e"
     
  

  # --------------------------------------------------------------------------
  # Phase 4: Release (dev branch only)
  # --------------------------------------------------------------------------
  release-commit:
    executor: node
    steps:
      - release

  release-nightly:
    executor: node
    steps:
      - release
    environment:
      COMMIT_MSG: "[release]"

# Workflow definition
workflows:
  version: 2

  # Build and test after each commit
  # Manually release on release branches -
  commit:
    jobs:
      - setup
      - lint: { requires: [setup] }
      - audit: { requires: [setup] }
      - test-unit: { requires: [setup] }
      - build: { requires: [setup] }
      - test-integration: { requires: [build] }
      - test-e2e:   { requires: [setup] }
      - release-commit:
          requires: [build, lint, audit, test-unit, test-integration]
          filters:
            <<: *release_branches

  # Test production 
  live:
    jobs:
      - setup
      - test-e2e:   { requires: [setup] }
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            <<: *release_branches